# Generated by Django 4.0.4 on 2022-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0020_alter_animal_id_alter_animaltype_id_alter_buyfood_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
